### ISSUE TITLE
TRYING SAME PROGRAM A6debug.ino IN ESP12E WITH A6 MODULE.

### ISSUE THREAD

**Issue by psatya111** [SensorsIot/A6-GSM-Module#2]
Hi I have connected A6gsm module with esp12f with gsm RX-> esp12f Tx and vice versa and i am trying to get the at command response in serial of esp12f .but i am not getting any thing.can any one help me.

code:-
#include <SoftwareSerial.h>

#define A6board Serial1

#ifndef A6board
SoftwareSerial A6board (D9, D10);
//#define A6baud 9600
#define A6baud 115200
#else
#define A6baud 115200
#endif

String hh;
char buffer[100];
char end_c[2];

void setup() {
  Serial.begin(115200);
  Serial.println(A6baud);
  A6board.begin(A6baud);
  Serial.println("Start");
  end_c[0] = 0x1a;
  end_c[1] = '\0';

}

void loop() {
  if (Serial.available()) {
    Serial.print("Serial available");
    hh = Serial.readStringUntil('\r');
    hh.toCharArray(buffer, hh.length() + 1);
    if (hh.indexOf("ende") == 0) {
      A6board.write(end_c);
      Serial.println("ende");
    } else{
      A6board.write(buffer);
      A6board.write('\r');
    }
  }
  if (A6board.available()) {
    Serial.print("Serial read");
    Serial.write(A6board.read());
  }
}

need help.
any help will appreciated .
mail id:psatya111@gmail.com

**Comment by SensorsIot** [comment]
I would first try with a normal Serial connection on 115200 baud. If this works, you can go on with a sketch.

**Comment by ubntomar** [comment]
hi friend, why use "ende" ? i dont understand. thankss very much

**Comment by SensorsIot** [comment]
Ende means end in German

**Comment by ubntomar** [comment]
uhm. ok thanks
